version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/notes:/app/notes
